[package]
name = "torus-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
ulid = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
bigdecimal = { version = "0.1.2", features = ["serde"]}
