[package]
name = "torus-database"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres", "chrono", "numeric"] }
bigdecimal = "0.1.2"
chrono = "0.4.19"
serde = { version = "1.0", features = ["derive"] }
envy = "0.4.2"
